title = ""
baseURL = "http://zhengxinzx.github.io/"
# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"
# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
publishDir = "docs"

# Change the default theme to be use when building the site with Hugo
theme = "FixIt"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "📰 Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "📒 Categories"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "🏷 Tags"
    url = "/tags/"
    weight = 3

[params]
  # FixIt theme version
  version = "0.2.X"
  # site default theme ["light", "dark", "auto"]
  defaultTheme = "auto"

  #  App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "zhengxin's Blog"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "/avatar.svg"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
    #  Android browser theme color
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"

  [params.search]
    enable = true
    # type of search engine ["lunr", "algolia", "fuse"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # FixIt 0.2.1 | NEW max number of results length
    maxResultLength = 10
    # FixIt 0.2.3 | NEW snippet length of the result
    snippetLength = 30
    # FixIt 0.2.1 | NEW HTML tag name of the highlight part in results
    highlightTag = "em"
    # FixIt 0.2.4 | NEW whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

  [params.header]
    # FixIt 0.2.13 | CHANGED desktop header mode ["sticky", "normal", "auto"]
    desktopMode = "sticky"
    # FixIt 0.2.13 | CHANGED mobile header mode ["sticky", "normal", "auto"]
    mobileMode = "auto"
    # FixIt 0.2.0 | NEW Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/avatar.svg"
      # title name
      name = "zhengxin's Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = "🥳"
      # FixIt 0.2.5 | NEW whether to use typeit animation for title name
      typeit = false
    # FixIt 0.2.12 | NEW Header subtitle config
    [params.header.subtitle]
      # subtitle name
      name = "Personal Blog to share interesting things"
      # whether to use typeit animation for subtitle name
      typeit = false

  [params.footer]
    enable = true
    #  Custom content (HTML format is supported)
    # For advanced use, see parameter `params.customFilePath.footer`
    custom = "xin.zheng.0459@outlook.com"
    #  whether to show Hugo and theme info
    hugo = false
    #  whether to show copyright info
    copyright = true
    #  whether to show the author
    author = true
    # Site creation year
    since = 2023
    #  whether to show total word count of site content
    wordCount = true
    #  Public network security only in China (HTML format is supported)
    gov = ""
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    #  Site creation time
    [params.footer.siteTime]
      enable = false
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "" # e.g. "2021-12-18T16:15:22+08:00"
    #  footer lines order, optional values: ["first", 0, 1, 2, 3, 4, 5, "last"]
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0

  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
    #  recently updated posts settings
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10

  #  List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  [params.tagcloud]
    enable = false
    min = 14 # Minimum font size in px
    max = 32 # Maximum font size in px
    peakCount = 10 # Maximum count of posts per tag
    orderby = "name" # Order of tags, optional values: ["name", "count"]

  # Home page config
  [params.home]
    #  amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "xin.zheng.0459@outlook.com"
      # URL of avatar shown in home page
      avatarURL = "/avatar.png"
      #  identifier of avatar menu link
      avatarMenu = ""
      #  title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "zhengxin's blog to share interesting things"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      #  disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6

  #  Social config about the author
  [params.social]
    GitHub = "zhengxinzx"
    Email = "xin.zheng.0459@outlook.com"

  #  Page config
  [params.page]
    #  whether to enable the author's avatar of the post
    authorAvatar = true
    #  whether to hide a page from home page
    hiddenFromHomePage = false
    #  whether to hide a page from search results
    hiddenFromSearch = false
    #  whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    #  if set to "force", images in the content will be forced to shown as the gallery.
    lightgallery = false
    #  whether to enable the ruby extended syntax
    ruby = true
    #  whether to enable the fraction extended syntax
    fraction = true
    #  whether to enable the fontawesome extended syntax
    fontawesome = true
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    #  whether to show the full text content in RSS
    rssFullText = false
    #  Page style ["narrow", "normal", "wide", ...]
    pageStyle = "normal"
    #   Gravatar is force-used as the author's avatar
    # gravatarForce = false
    #  Auto Bookmark Support
    # If true, save the reading progress when closing the page.
    autoBookmark = false
    #  whether to enable wordCount
    wordCount = true
    #  whether to enable readingTime
    readingTime = true
    #  end of post flag
    endFlag = ""
    #  whether to enable instant.page
    instantPage = false

    #  Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      #  whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
      #  position of TOC ["left", "right"]
      position = "left"

    #  Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      #  whether to show the edit button of the code block
      edit = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10

  #  Mermaid config
  [params.mermaid]
    # For values, see https://mermaid.js.org/config/theming.html#available-themes
    themes = ["default", "dark"]

  #  Back to top
  [params.backToTop]
    enable = true
    # Scroll percent label in b2t button
    scrollpercent = false

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ########## necessary configurations ##########
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    ########## necessary configurations ##########
    guessSyntax = true
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author config
[author]
  name = "zhengxin"
  email = "xin.zheng.0459@outlook.com"
  link = "https://github.com/zhengxinzx"
  avatar = "/avatar.png" # 